version: '3.6'

services:
  #api:
  #  build: 
  #    context: .
  #    dockerfile: src\1 - Services\Api\Dockerfile
  #  container_name: GraphCoutries-Api
  #  ports:
  #      - 3000:44306
  #  networks:
  #      - backend 
  #  depends_on:
  #      - db

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: countries
    ports:
        - 5432:5432
    networks:
        - backend
    volumes:
        - postgres-data:/var/lib/postgresql/data

  #flyway:
  #  image: flyway/flyway:7
  #  restart: on-failure
  #  command: -url=jdbc:postgresql://localhost:5432/Countries -schemas=public -user=postgres -password=docker migrate
  #  environment:
  #      - FLYWAY_EDITION=community
  #  volumes:
  #      - ./postgresdb-script:/flyway/sql
  #  depends_on:
  #      - db

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:
