version: '3.6'

services:
  #api:
  # build: 
  #   context: .
  #   dockerfile: src\1 - Services\Api\Dockerfile
  # container_name: graphcoutries-api
  # ports:
  #    - 5000:5000
  # networks:
  #   - backend 

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

  #db-seed:
  #  image: postgres:13-alpine
  #  build:
  #    context: .
  #  container_name: db-seed
  #  depends_on:
  #   - db

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:
