DROP DATABASE IF EXISTS Countries;    

CREATE DATABASE Countries;    


CREATE TABLE "CountryData" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"JsonData" text NULL,
	CONSTRAINT "PK_CountryData" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Email" text NULL,
	"Senha" text NULL,
	CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

INSERT INTO "Users" ("Email", "Senha") VALUES ('usuario@admin.com.br', '123456');
